#* All services to be used will be declared
services:

  #* Service name
    frontend:
      #* Image to use
      image: node:20.15.1-alpine
      init: true
      #* Directory where you will work
      working_dir: /home/dev
      #* Container name
      container_name: KananPassSite
      command: sh -c "npm i && npm run dev"
      #* Port exhibition
      ports:
        - 3000:3000
      #* Volume where information persists
      volumes:
        - .:/home/dev
      #* Restart the container
      restart: unless-stopped